// Inside components/ResultsDisplay.tsx

const handleMint = () => {
  const canvas = canvasRef.current;
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  // 1. Setup Document (A4 Vertical Ratio high-res)
  canvas.width = 1240;
  canvas.height = 1754;
  
  // Background: Clean White Paper
  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Fetch User Name for the Header
  const profile = JSON.parse(localStorage.getItem('tpe_user_profile') || '{"name": "OPERATIVE"}');
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: '2-digit' }).toUpperCase();

  // 2. Draw Header Block (The "Official" Look)
  ctx.fillStyle = '#0F2A4D'; // Navy
  ctx.font = 'bold 40px monospace'; // Monospaced for "Typewriter" feel
  ctx.textAlign = 'left';
  
  const leftMargin = 100;
  let yCursor = 120;
  const lineHeight = 60;

  ctx.fillText(`MEMORANDUM FOR RECORD`, leftMargin, yCursor);
  yCursor += lineHeight * 1.5;
  
  ctx.font = '32px monospace';
  ctx.fillText(`TO:      ${profile.name.toUpperCase()}`, leftMargin, yCursor);
  yCursor += lineHeight;
  ctx.fillText(`FROM:    THE PRINCIPLE ENGINE`, leftMargin, yCursor);
  yCursor += lineHeight;
  ctx.fillText(`DATE:    ${dateStr}`, leftMargin, yCursor);
  yCursor += lineHeight;
  ctx.fillText(`SUBJECT: PROTOCOL FOR '${data.category}'`, leftMargin, yCursor);
  yCursor += lineHeight;

  // The "Classified" Stamp
  ctx.fillStyle = '#D4AF37'; // Gold
  ctx.fillText(`STATUS:  KINGDOM BUSINESS // AUTHORIZED`, leftMargin, yCursor);
  
  // Divider Line
  yCursor += lineHeight;
  ctx.beginPath();
  ctx.moveTo(leftMargin, yCursor);
  ctx.lineTo(canvas.width - leftMargin, yCursor);
  ctx.strokeStyle = '#0F2A4D';
  ctx.lineWidth = 4;
  ctx.stroke();

  // 3. The Core Content
  yCursor += lineHeight * 2;
  ctx.fillStyle = '#0F2A4D';
  
  // SECTION 1: THE PRINCIPLE
  ctx.font = 'bold 28px sans-serif';
  ctx.fillText("1. THE PRINCIPLE", leftMargin, yCursor);
  yCursor += 50;
  
  ctx.font = 'italic 36px serif';
  wrapText(ctx, `"${data.corePrinciple}"`, leftMargin, yCursor, 1040, 50);
  yCursor += 100; // Add buffer after wrapped text

  // SECTION 2: THE AUTHORITY
  ctx.font = 'bold 28px sans-serif';
  ctx.fillText("2. THE AUTHORITY", leftMargin, yCursor);
  yCursor += 50;
  ctx.font = '30px serif';
  ctx.fillText(data.sourceReference, leftMargin, yCursor);
  yCursor += 80;

  // SECTION 3: EXECUTION PROTOCOL
  ctx.font = 'bold 28px sans-serif';
  ctx.fillText("3. EXECUTION STEPS", leftMargin, yCursor);
  yCursor += 50;

  ctx.font = '24px monospace';
  data.actionPlan.forEach((step, i) => {
      const stepText = `[0${i+1}] ${step}`;
      // Checkbox visual
      ctx.strokeRect(leftMargin, yCursor - 25, 30, 30);
      // Text wrap for steps
      yCursor = wrapText(ctx, stepText, leftMargin + 50, yCursor, 950, 40); 
      yCursor += 20; // Extra padding between steps
  });

  // Footer
  ctx.fillStyle = 'rgba(15, 42, 77, 0.4)';
  ctx.font = '20px sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText("Generated by The Principle Engine | Soli Deo Gloria", canvas.width / 2, canvas.height - 50);

  // Download Trigger
  const link = document.createElement('a');
  link.download = `SOP-${data.category.replace(/\s+/g, '-')}.png`;
  link.href = canvas.toDataURL();
  link.click();
};

// Helper function to handle text wrapping on Canvas
function wrapText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, maxWidth: number, lineHeight: number) {
    const words = text.split(' ');
    let line = '';
    let currentY = y;

    for(let n = 0; n < words.length; n++) {
      const testLine = line + words[n] + ' ';
      const metrics = ctx.measureText(testLine);
      const testWidth = metrics.width;
      if (testWidth > maxWidth && n > 0) {
        ctx.fillText(line, x, currentY);
        line = words[n] + ' ';
        currentY += lineHeight;
      } else {
        line = testLine;
      }
    }
    ctx.fillText(line, x, currentY);
    return currentY + lineHeight; // Return new Y position
}